name: jpeg_turbo_resizer
description: "A custom Flutter plugin for Windows that enables fast and efficient image resizing using the libjpeg-turbo library. This initial release focuses on resizing JPEG images with high performance. More features, such as additional image processing capabilities, will be added in future updates."
version: 0.0.1
homepage: "https://github.com/sreeharikodavalam/jpeg_turbo_resizer_flutter"

author:
  name: Sreehari Kodavalam
  email: sreeharikodavalam@gmail.com

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  path: ^1.9.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  plugin:
    platforms:
      windows:
        pluginClass: JpegTurboResizerPluginCApi